server.port: -1

spring:
  application.name: sigure-task

  jackson.serialization:
    write-dates-as-timestamps: false

  rabbitmq:
    addresses: 127.0.0.1
    port: 5672

  cloud.stream.bindings:
    output:
     destination: test1
     contentType: application/json